server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# 配置mybatis实体和xml映射
mybatis:
  ## 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 文件上传配置
file:
  upload-path: ${user.dir}/springboot/files


# 支付宝配置
ali-pay:
  appId: 9021000162603115
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRL0Jn4hCexENJteRBmgk37YMW3xQd8Am1c5Bi9Md7oue7VWwogSTduqTWyemFf99ClIDwqyM8q6Phahu78Jcl/wuB/WbCHZALbPbEYX5LUsCBVtpMbmX6pxGKNBG89rv/eW0qTWVUxKVQ2cqVkMAFefpf1fmZImiJh1bzJUY2c65/rke/lVwdPFQSDJKU4oleO64rN5cPf1PdZwmh8HmFJxfirV4DgN7XHGPsotEhFyHMzq2s0p8/4kW+wJjRflHFfpqeAfcAMg1wo2rb5I3r22KyD4hZ7ElsHQX3jNOra4zkMkeMl8ns2P7gpNxgYy+gBoCOyrdvA+wqGAm/M0wHAgMBAAECggEAKiIH6HPflOOqD1sc6bjVEgj4cQu+H84IU0M9VKpqtcOZ8nCg2cRYuYwvyDGCdn6cgQrtvGo96J57CbCsaccxZhJ0+X1bc9v2cIpntqgAacWTHjXhVir3p10SpwPjXe5Qspw/hPY/APGsdCEwPGVshGpYsbU8ISeuJLNFFXzsumI1tUiC+F3U0x4xLZ3Utb2Ljt22zdcxcRdu/hXw2HJNyuKoXrOW+35ZX9mO/Jqdjgw6l8+7upyELH+BMkkKZe4eEhf7Ssraan4ZWyYch9CUhVpQ7wwgQRsJw/4mNcoj1i3HtOmR63tUiy4zSKVLRXAoji6ygG/c6b3hdyPhFxwDWQKBgQD+ga+Fu6x1X7QTtNBkiiOs7gNzxSCBsHQ6KsA4giDLg8Ktj5/JDONfnY5o2kVIM3Fuv7BzWWqtod/+KKvibqf3HRFCdbq9e+q13tEgNmIRC8x7x0MvX3kB1wbZuFPvQJCI0BwrDEdRhJrrsi9Wv3Ij5PvTa7qAPqvSwh9xit1ZywKBgQCSCVpFQQx80pIBj7X2rCFVAm80QOLaoIP8SzJ+m53K+5W3eT2BKYfhsnf9K1pXuOZJUhV4rrChxV71F2Pc4fnEmbpU5ytOLGq3sv6e0+fWuR62w9tkXNBOEd0xZy5RSvkx/tQ2W40U1cWSn/0AEQTi40Hoafr4e6S2SOZ15Px/NQKBgD6cswzIhf3+RHQQqLADWBGEIK9LkNq3CXEB8XY1dVH8IVnHmrzAgfOU9GMRR7gih8aCPCu0lM0QpOWHJfo31PSzXvqlsgJJyQ1jOrmdB3VAHNdax0mRSFjOiK3pbiTPEn/GCxgAFk+UuvQ/SuwhfzgbbmSt/RztziG0hj3NtvUPAoGAV8i9dbHTctkVIVEk3aG865/p/uweMbOZgzgko0yh/pla9w4vNYwkfTxNumasCN1BuMNZ2tCPpr7BBO1Jf0ZrYI3UHyNSucwjXkd/nTPeQgnHd6+mGt9b7AH7B65xfjZmM3JuWDqSRPr3p9r6N2cDm+tl+/JxBZs1eMm7lxTN3x0CgYAPntI52K0pL0Mx5s3Gc3C9PaC4sDKYi0IGWa9ErXo1iocJX/0F0lyWleWKd/C9ZW6wuJOjayONiatbT+ck7ZW1tgJ/1KaFGJZIYTNwfo0okoUlsFGk+eI14+9JDfV2XBhGqYvVR3uwSXdad1q41m3IzvM7wKWhtrbIPKt+gnAsRg==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp+t1SttJOv6Rw5x+1onijRDcMX2rwSr1y0QcopRWD3cxSisDY7fYb/L5OZyekA0lJOw8Ih+HZPy9476GCU35UpvQsJ1xUBjNWNPfhtRxQX+WygDXQU10rrp34XLvvQ4NJBm7sumqy2N6ws3YFlWd49PTlKM3JeUIXaSubkSK+viMwvbSE3MGi4LLGoTSwg2N/3d2kA6UZFUOwgjUtXRDGhq3VosZdzF1bzgQwv1IN57GhiQ5z9K0BW3+83RvOijvbRzwHj8ZnycY77R1H9qZ3bYSbAsX0GG0eTWKSSLX6oK7XkFmph1zbUwlToVF+/LJt3/YaH6Uk3IAPpFxMANU5QIDAQAB
  # 回调地址
  #notifyUrl:  http://taa76e83.natappfree.cc/alipay/notify
#  notifyUrl: http://localhost:8080/alipay/notify
#  returnUrl: http://localhost:8080/orders
  notifyUrl: http://localhost:8080/pay/alipay/callback
  returnUrl: http://localhost:8080/pay/orders
  # 网关地址
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 编码
  charset: UTF-8
  # 签名类型
  signType: RSA2